version: '2'
services:
    projet_csid-app:
        image: projet_csid
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://projet_csid-mysql:3306/projet_csid?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    projet_csid-mysql:
        extends:
            file: mysql.yml
            service: projet_csid-mysql
